### ISSUE TITLE
get_top_peak_gene_pairs returns empty data frame

### ISSUE THREAD

**Issue by abearab** [ChangSuBiostats/scMultiMap-archived#1]
Hello, Thanks for sharing this very useful tool! I'm very excited to use it in my class project at UCSF and it would be great if you can provide some guidance on how I can debug my current code!

In this notebook I'm trying to create the input objects and follow your instructions. https://github.com/abearab/BMI-206-Class-Project/blob/abe/individual_abe.ipynb

However, I keep getting empty `pairs_df`! Do you know what could be wrong and how I can fix it? I'm pretty sure it's not an issue with `scMultiMap` and it comes from my limited knowledge about single cell analysis in R!

Thanks for your time and attention!

**Comment by ChangSuBiostats** [comment]
Hi Abe,

Thanks for your interest in our work! scMultiMap is currently under revision at Nature Communications and welcomes your feedback.

As I don’t have access to your Seurat object, my best suggestion is to suggest you run the codes within the function ‘get_top_peak_gene_pairs()’ line by line, and check which step gives you unexpected results. get_top_peak_gene_pairs()  is defined at https://github.com/ChangSuBiostats/scMultiMap/blob/master/R/utils.R#L22

My other suggestion is to make sure that your peak data are fragment counts instead of insertion-based counts. Only fragment counts e.g. from MACS2 can be properly modeled by Poisson. See reference: https://www.nature.com/articles/s41592-023-02112-6

I hope this helps. Please let me know if you have any questions on using scMultiMap.

Best,
Chang

From: Abolfazl (Abe) ***@***.***>
Date: Monday, December 9, 2024 at 9:40 PM
To: ChangSuBiostats/scMultiMap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [ChangSuBiostats/scMultiMap] get_top_peak_gene_pairs returns empty data frame (Issue #1)

Hello, Thanks for sharing this very useful tool! I'm very excited to use it in my class project at UCSF and it would be great if you can provide some guidance on how I can debug my current code!

In this notebook I'm trying to create the input objects and follow your instructions. https://github.com/abearab/BMI-206-Class-Project/blob/abe/individual_abe.ipynb

However, I keep getting empty pairs_df! Do you know what could be wrong and how I can fix it? I'm pretty sure it's not an issue with scMultiMap and it comes from my limited knowledge about single cell analysis in R!

Thanks for your time and attention!

**Comment by abearab** [comment]
Hi Chang, thanks for your quick response. I'm going to check the code section you shared and will get back to you asap. In the meantime, here is a link to the `SCENT` object we generated previously and I used it in the notebook to create my Seurat object:
- https://ucsf.box.com/s/ory10beiaadvzaku8gy765273jpcm3ns

**Comment by abearab** [comment]
To my understanding this is the part I get an empty table https://github.com/ChangSuBiostats/scMultiMap/blob/56fded216d492010a097f68c141757b9dcbc4584/R/utils.R#L48

@ChangSuBiostats any thoughts?

**Comment by abearab** [comment]
I think I failed in my `annotation` object. This [tutorial](https://stuartlab.org/signac/articles/pbmc_multiomic) added "chr" to chromosome names and this could solve my issue!

```R
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevels(annotation) <- paste0('chr', seqlevels(annotation))
```
